name: Publish Python Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test:
    steps:
      - uses: ./.github/actions/test
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-publish-pip-${{ hashFiles('**/setup.cfg') }}
          restore-keys: |
            - ${{ runner.os }}-publish-pip-
      - name: Install dependencies
        run: |
          pip install setuptools wheel twine
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
